version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    restart: always

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "4000:3000"
    restart: always
