services:
  web:
    image: humming-vision-web
    ports:
      - "3000:3000"
    restart: always

  api:
    image: humming-vision-api
    ports:
      - "4000:3000"
    restart: always
    env_file:
      - .env.api
    volumes:
      - ./global-bundle.pem:/app/dist/global-bundle.pem:ro
