export const ENV_API_END_POINT_KEY = "API_END_POINT";
export const NODE_ENV_KEY = "NODE_ENV";

export const ENV_JWT_SECRET_KEY = "JWT_SECRET";
export const ENV_JWT_ACCESS_EXPIRES = "JWT_ACCESS_EXPIRES";
export const ENV_JWT_REFRESH_EXPIRES = "JWT_REFRESH_EXPIRES";

export const ENV_NAVER_CLIENT_ID_KEY = "NAVER_CLIENT_ID";
export const ENV_NAVER_SECRET_KEY = "NAVER_SECRET";
