export const ENV_API_END_POINT_KEY = "NEXT_PUBLIC_API_END_POINT";
export const NODE_ENV_KEY = "NEXT_PUBLIC_NODE_ENV";

export const ENV_JWT_SECRET_KEY = "NEXT_PUBLIC_JWT_SECRET";
export const ENV_JWT_ACCESS_EXPIRES = "NEXT_PUBLIC_JWT_ACCESS_EXPIRES";
export const ENV_JWT_REFRESH_EXPIRES = "NEXT_PUBLIC_JWT_REFRESH_EXPIRES";

export const ENV_NAVER_CLIENT_ID_KEY = "NEXT_PUBLIC_NAVER_CLIENT_ID";
export const ENV_NAVER_SECRET_KEY = "NEXT_PUBLIC_NAVER_SECRET";
