name: Build and Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Turbo
        run: npm install -g turbo

      - name: Prune for web
        run: npx turbo prune web --docker

      - name: Prune for api
        run: npx turbo prune api --docker

      - name: Build Docker images
        run: |
          docker build -f out/docker/apps/web/Dockerfile -t humming-vision-web out/docker
          docker build -f out/docker/apps/api/Dockerfile -t humming-vision-api out/docker

      - name: Save images to tar
        run: |
          docker save humming-vision-web > web.tar
          docker save humming-vision-api > api.tar

      - name: Copy Docker images to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "web.tar,api.tar"
          target: "/home/ec2-user"

      - name: Remote Deploy (load + restart)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker load < web.tar
            docker load < api.tar
            docker stop web || true && docker rm web || true
            docker stop api || true && docker rm api || true
            docker run -d --name web -p 3000:3000 humming-vision-web
            docker run -d --name api -p 4000:3000 humming-vision-api
